#include <windows.h>

#define VER_FILEFLAGSMASK			VS_FFI_FILEFLAGSMASK
#define VER_FILEOS          		VOS_NT_WINDOWS32

#ifdef _DEBUG
	#define VER_FILEFLAGS				1
#else
	#define VER_FILEFLAGS				0
#endif



#define VER_PRODUCTNAME_STR 		"Modified CompuScope driver"
#define VER_COMPANYNAME_STR 		"Unknown"
#define VER_LEGALCOPYRIGHT_YEARS    	" 2010"
#define VER_LEGALCOPYRIGHT_STR		"(c) " VER_COMPANYNAME_STR VER_LEGALCOPYRIGHT_YEARS
#define VER_LEGALTRADEMARKS_STR     	""
#define VER_FILEVERSION			VER_PRODUCTVERSION
#define VER_FILEVERSION_STR		VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_DW       	(0x01000000 | VER_PRODUCTBUILD)

#define VER_FILETYPE				VFT_DRV
#define VER_FILESUBTYPE				VFT2_DRV_SYSTEM

#define VER_PRODUCTVERSION_CSDK_STR  "0, 0, 0, 0"
#define VER_PRODUCTVERSION_CSDK      0,0,0,00
#define VER_PRODUCTNAME_CSDK_STR     "Modified CompuScope C/C# SDK"
